---
- name: kafka
  hosts: master
  gather_facts: no
 
  vars:
    ansible_become_pass: "vagrant"

  tasks:
    - name: Copy .yml files to k8s master
      copy: 
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: vagrant
        group: vagrant
      with_items:
        - { src: "servicemonitor/jmx-exporter-servicemonitor.yaml", dest: "/home/vagrant/jmx-exporter-servicemonitor.yaml" }

    - name: Run kubectl create --filename jmx-exporter-servicemonitor.yaml
      become: yes
      shell: "kubectl create --filename jmx-exporter-servicemonitor.yaml"
      environment:
        KUBECONFIG: /home/vagrant/.kube/config
      register: create_jmx_exporter_servicemonitor

    - name: Debug create_jmx_exporter_servicemonitor
      debug: 
        var: create_jmx_exporter_servicemonitor
